theme: jekyll-theme-minimal

#Name of webite
title: Welcome to Callum's homepage!
description: Come to this site for all your Callum related content.

<a href="https://www.linkedin.com/in/callumrwayman/">LinkedIn</a>

